name: hugetooth

packages:
  - apps/**
  - packages/**

ide:
  intellij:
    enabled: false

scripts:
  analyze:
    exec: dart analyze .

  drb:
    exec: dart run build_runner build

  drbd:
    exec: dart run build_runner build --delete-conflicting-outputs

  test:
    exec: dart test
