name: hugetooth

packages:
  - apps/**
  - packages/**

ide:
  intellij:
    enabled: false

scripts:
  analyze:
    exec: dart analyze .

  drb:
    exec: dart run build_runner build

  drbd:
    exec: dart run build_runner build --delete-conflicting-outputs

  dtest:
    exec: dart test
    packageFilters:
      scope: auth_core

  ftest:
    exec: flutter test
    packageFilters:
      scope: [auth_firebase, fluter_starter_template]
