name: hugetooth

packages:
  - apps/**
  - packages/**

ide:
  intellij:
    enabled: false

command:
  bootstrap:
    environment:
      sdk: ^3.5.1
      flutter: ^3.24.0

    dependencies:
      cloud_firestore: ^5.3.0
      collection: ^1.18.0
      device_info_plus: ^10.1.0
      dynamic_color: ^1.7.0
      equatable: ^2.0.5
      firebase_analytics: ^11.3.0
      firebase_auth: ^5.2.0
      firebase_core: ^3.4.0
      firebase_crashlytics: ^4.1.0
      firebase_storage: ^12.2.0
      flutter_animate: ^4.5.0
      flutter_displaymode: ^0.6.0
      flutter_dotenv: ^5.1.0
      flutter_gen: any
      flutter_riverpod: ^2.5.1
      freezed: ^2.5.7
      freezed_annotation: ^2.4.4
      intl: any
      json_annotation: ^4.9.0
      logger: ^2.3.0
      uuid: ^4.4.0

    dev_dependencies:
      build_runner: ^2.4.12
      custom_lint: ^0.6.5
      flutter_launcher_icons: ^0.13.1
      flutter_test:
        sdk: flutter
      json_serializable: ^6.8.0
      mocktail: ^1.0.4
      riverpod_generator: ^2.4.3
      riverpod_lint: ^2.3.13
      very_good_analysis: ^6.0.0

scripts:
  analyze:
    exec: dart analyze .

  drb:
    exec: dart run build_runner build

  drbd:
    exec: dart run build_runner build --delete-conflicting-outputs

  dtest:
    exec: dart test
    packageFilters:
      scope: auth_core

  ftest:
    exec: flutter test
    packageFilters:
      scope: [auth_firebase, fluter_starter_template]

  upgrade:
    exec: flutter pub upgrade

  pubget:
    exec: flutter pub get

  clean:
    exec: flutter clean
