name: hugetooth

environment:
  sdk: "^3.3.0"

dev_dependencies:
  melos: ^6.0.0
  very_good_analysis: ^5.1.0
# dependencies:
#   freezed_annotation: ^2.4.1
#   json_annotation: ^4.9.0
# dev_dependencies:
#   build_runner: ^2.4.9
#   freezed: ^2.5.2
#   json_serializable: ^6.8.0
