name: flutter_starter_template
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.4.0"
  flutter: "^3.22.0"

dependencies:
  analytics_core:
    path: ../../packages/analytics_core
  # analytics_firebase:
  #   path: ../../packages/analytics_firebase
  auth_core:
    path: ../../packages/auth_core
  # auth_firebase:
  #   path: ../../packages/auth_firebase
  error_logging_core:
    path: ../../packages/error_logging_core
  # error_logging_crashlytics:
  #   path: ../../packages/error_logging_crashlytics
  flutter:
    sdk: flutter
  flutter_gen: any
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  go_router: ^14.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  purchases_core:
    path: ../../packages/purchases_core
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
